<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class City_20_Nagano_Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $table_name = 'cities';

        $data = [
            [
                'id' => 851,
                'code' => '202011',
                'prefecture_id' => 20,
                'name_en' => 'Naganoshi',
                'name_jp' => '長野市',
            ],
            [
                'id' => 852,
                'code' => '202029',
                'prefecture_id' => 20,
                'name_en' => 'Matsumotoshi',
                'name_jp' => '松本市',
            ],
            [
                'id' => 853,
                'code' => '202037',
                'prefecture_id' => 20,
                'name_en' => 'Uetadashi',
                'name_jp' => '上田市',
            ],
            [
                'id' => 854,
                'code' => '202045',
                'prefecture_id' => 20,
                'name_en' => 'Okayashi',
                'name_jp' => '岡谷市',
            ],
            [
                'id' => 855,
                'code' => '202053',
                'prefecture_id' => 20,
                'name_en' => 'Iidashi',
                'name_jp' => '飯田市',
            ],
            [
                'id' => 856,
                'code' => '202061',
                'prefecture_id' => 20,
                'name_en' => 'Suwashi',
                'name_jp' => '諏訪市',
            ],
            [
                'id' => 857,
                'code' => '202070',
                'prefecture_id' => 20,
                'name_en' => 'Suzakash',
                'name_jp' => '須坂市',
            ],
            [
                'id' => 858,
                'code' => '202088',
                'prefecture_id' => 20,
                'name_en' => 'Komoroshi',
                'name_jp' => '小諸市',
            ],
            [
                'id' => 859,
                'code' => '202096',
                'prefecture_id' => 20,
                'name_en' => 'Inashi',
                'name_jp' => '伊那市',
            ],
            [
                'id' => 860,
                'code' => '202100',
                'prefecture_id' => 20,
                'name_en' => 'Komaganeshi',
                'name_jp' => '駒ヶ根市',
            ],
            [
                'id' => 861,
                'code' => '202118',
                'prefecture_id' => 20,
                'name_en' => 'Nakanoshi',
                'name_jp' => '中野市',
            ],
            [
                'id' => 862,
                'code' => '202126',
                'prefecture_id' => 20,
                'name_en' => 'Oomachishi',
                'name_jp' => '大町市',
            ],
            [
                'id' => 863,
                'code' => '202134',
                'prefecture_id' => 20,
                'name_en' => 'Iiyamashi',
                'name_jp' => '飯山市',
            ],
            [
                'id' => 864,
                'code' => '202142',
                'prefecture_id' => 20,
                'name_en' => 'Chinoshi',
                'name_jp' => '茅野市',
            ],
            [
                'id' => 865,
                'code' => '202151',
                'prefecture_id' => 20,
                'name_en' => 'Shiojirishi',
                'name_jp' => '塩尻市',
            ],
            [
                'id' => 866,
                'code' => '202177',
                'prefecture_id' => 20,
                'name_en' => 'Sakushi',
                'name_jp' => '佐久市',
            ],
            [
                'id' => 867,
                'code' => '202185',
                'prefecture_id' => 20,
                'name_en' => 'Chikumashi',
                'name_jp' => '千曲市',
            ],
            [
                'id' => 868,
                'code' => '202193',
                'prefecture_id' => 20,
                'name_en' => 'Toumishi',
                'name_jp' => '東御市',
            ],
            [
                'id' => 869,
                'code' => '202207',
                'prefecture_id' => 20,
                'name_en' => 'Azuminoshi',
                'name_jp' => '安曇野市',
            ],
            [
                'id' => 870,
                'code' => '203033',
                'prefecture_id' => 20,
                'name_en' => 'Koumimachi',
                'name_jp' => '小海町',
            ],
            [
                'id' => 871,
                'code' => '203041',
                'prefecture_id' => 20,
                'name_en' => 'Kawakamimura',
                'name_jp' => '川上村',
            ],
            [
                'id' => 872,
                'code' => '203050',
                'prefecture_id' => 20,
                'name_en' => 'Minamimakimura',
                'name_jp' => '南牧村',
            ],
            [
                'id' => 873,
                'code' => '203068',
                'prefecture_id' => 20,
                'name_en' => 'Minamiaikimura',
                'name_jp' => '南相木村',
            ],
            [
                'id' => 874,
                'code' => '203076',
                'prefecture_id' => 20,
                'name_en' => 'Kitaikimura',
                'name_jp' => '北相木村',
            ],
            [
                'id' => 875,
                'code' => '203092',
                'prefecture_id' => 20,
                'name_en' => 'Sakuhomachi',
                'name_jp' => '佐久穂町',
            ],
            [
                'id' => 876,
                'code' => '203211',
                'prefecture_id' => 20,
                'name_en' => 'Karuizawamachi',
                'name_jp' => '軽井沢町',
            ],
            [
                'id' => 877,
                'code' => '203238',
                'prefecture_id' => 20,
                'name_en' => 'Miyotamachi',
                'name_jp' => '御代田町',
            ],
            [
                'id' => 878,
                'code' => '203246',
                'prefecture_id' => 20,
                'name_en' => 'Tateshinamachi',
                'name_jp' => '立科町',
            ],
            [
                'id' => 879,
                'code' => '203491',
                'prefecture_id' => 20,
                'name_en' => 'Aokimura',
                'name_jp' => '青木村',
            ],
            [
                'id' => 880,
                'code' => '203505',
                'prefecture_id' => 20,
                'name_en' => 'Nagawamachi',
                'name_jp' => '長和町',
            ],
            [
                'id' => 881,
                'code' => '203611',
                'prefecture_id' => 20,
                'name_en' => 'Shimosuwamachi',
                'name_jp' => '下諏訪町',
            ],
            [
                'id' => 882,
                'code' => '203629',
                'prefecture_id' => 20,
                'name_en' => 'Fujimimachi',
                'name_jp' => '富士見町',
            ],
            [
                'id' => 883,
                'code' => '203637',
                'prefecture_id' => 20,
                'name_en' => 'Haramura',
                'name_jp' => '原村',
            ],
            [
                'id' => 884,
                'code' => '203823',
                'prefecture_id' => 20,
                'name_en' => 'Tatsunomachi',
                'name_jp' => '辰野町',
            ],
            [
                'id' => 885,
                'code' => '203831',
                'prefecture_id' => 20,
                'name_en' => 'Minowamachi',
                'name_jp' => '箕輪町',
            ],
            [
                'id' => 886,
                'code' => '203840',
                'prefecture_id' => 20,
                'name_en' => 'Iijimamachi',
                'name_jp' => '飯島町',
            ],
            [
                'id' => 887,
                'code' => '203858',
                'prefecture_id' => 20,
                'name_en' => 'Minamiminowamura',
                'name_jp' => '南箕輪村',
            ],
            [
                'id' => 888,
                'code' => '203866',
                'prefecture_id' => 20,
                'name_en' => 'Nakagawamura',
                'name_jp' => '中川村',
            ],
            [
                'id' => 889,
                'code' => '203882',
                'prefecture_id' => 20,
                'name_en' => 'Miyadamura',
                'name_jp' => '宮田村',
            ],
            [
                'id' => 890,
                'code' => '204021',
                'prefecture_id' => 20,
                'name_en' => 'Matsukawamachi',
                'name_jp' => '松川町',
            ],
            [
                'id' => 891,
                'code' => '204030',
                'prefecture_id' => 20,
                'name_en' => 'Takamorimachi',
                'name_jp' => '高森町',
            ],
            [
                'id' => 892,
                'code' => '204048',
                'prefecture_id' => 20,
                'name_en' => 'Anancho',
                'name_jp' => '阿南町',
            ],
            [
                'id' => 893,
                'code' => '204072',
                'prefecture_id' => 20,
                'name_en' => 'Achimura',
                'name_jp' => '阿智村',
            ],
            [
                'id' => 894,
                'code' => '204099',
                'prefecture_id' => 20,
                'name_en' => 'Hirayamamura',
                'name_jp' => '平谷村',
            ],
            [
                'id' => 895,
                'code' => '204102',
                'prefecture_id' => 20,
                'name_en' => 'Nebamura',
                'name_jp' => '根羽村',
            ],
            [
                'id' => 896,
                'code' => '204111',
                'prefecture_id' => 20,
                'name_en' => 'Shimojomyomura',
                'name_jp' => '下條村',
            ],
            [
                'id' => 897,
                'code' => '204129',
                'prefecture_id' => 20,
                'name_en' => 'Urukimura',
                'name_jp' => '売木村',
            ],
            [
                'id' => 898,
                'code' => '204137',
                'prefecture_id' => 20,
                'name_en' => 'Tenryuumura',
                'name_jp' => '天龍村',
            ],
            [
                'id' => 899,
                'code' => '204145',
                'prefecture_id' => 20,
                'name_en' => 'Yasuokamura',
                'name_jp' => '泰阜村',
            ],
            [
                'id' => 900,
                'code' => '204153',
                'prefecture_id' => 20,
                'name_en' => 'Takagimura',
                'name_jp' => '喬木村',
            ],
            [
                'id' => 901,
                'code' => '204161',
                'prefecture_id' => 20,
                'name_en' => 'Toyookamura',
                'name_jp' => '豊丘村',
            ],
            [
                'id' => 902,
                'code' => '204170',
                'prefecture_id' => 20,
                'name_en' => 'Ooshikamura',
                'name_jp' => '大鹿村',
            ],
            [
                'id' => 903,
                'code' => '204226',
                'prefecture_id' => 20,
                'name_en' => 'Agematsumachi',
                'name_jp' => '上松町',
            ],
            [
                'id' => 904,
                'code' => '204234',
                'prefecture_id' => 20,
                'name_en' => 'Nagisomachi',
                'name_jp' => '南木曽町',
            ],
            [
                'id' => 905,
                'code' => '204251',
                'prefecture_id' => 20,
                'name_en' => 'Kisomura',
                'name_jp' => '木祖村',
            ],
            [
                'id' => 906,
                'code' => '204293',
                'prefecture_id' => 20,
                'name_en' => 'Outakimura',
                'name_jp' => '王滝村',
            ],
            [
                'id' => 907,
                'code' => '204307',
                'prefecture_id' => 20,
                'name_en' => 'Ookumura',
                'name_jp' => '大桑村',
            ],
            [
                'id' => 908,
                'code' => '204323',
                'prefecture_id' => 20,
                'name_en' => 'Kisomachi',
                'name_jp' => '木曽町',
            ],
            [
                'id' => 909,
                'code' => '204463',
                'prefecture_id' => 20,
                'name_en' => 'Omimura',
                'name_jp' => '麻績村',
            ],
            [
                'id' => 910,
                'code' => '204480',
                'prefecture_id' => 20,
                'name_en' => 'Ikusakamura',
                'name_jp' => '生坂村',
            ],
            [
                'id' => 911,
                'code' => '204501',
                'prefecture_id' => 20,
                'name_en' => 'Yamagatamamura',
                'name_jp' => '山形村',
            ],
            [
                'id' => 912,
                'code' => '204510',
                'prefecture_id' => 20,
                'name_en' => 'Asahimura',
                'name_jp' => '朝日村',
            ],
            [
                'id' => 913,
                'code' => '204528',
                'prefecture_id' => 20,
                'name_en' => 'Chikuhoku-mura',
                'name_jp' => '筑北村',
            ],
            [
                'id' => 914,
                'code' => '204811',
                'prefecture_id' => 20,
                'name_en' => 'Ikedamachi',
                'name_jp' => '池田町',
            ],
            [
                'id' => 915,
                'code' => '204820',
                'prefecture_id' => 20,
                'name_en' => 'Matsumotomura',
                'name_jp' => '松川村',
            ],
            [
                'id' => 916,
                'code' => '204854',
                'prefecture_id' => 20,
                'name_en' => 'Hakubamura',
                'name_jp' => '白馬村',
            ],
            [
                'id' => 917,
                'code' => '204862',
                'prefecture_id' => 20,
                'name_en' => 'Otarimura',
                'name_jp' => '小谷村',
            ],
            [
                'id' => 918,
                'code' => '205214',
                'prefecture_id' => 20,
                'name_en' => 'Sakakimachi',
                'name_jp' => '坂城町',
            ],
            [
                'id' => 919,
                'code' => '205419',
                'prefecture_id' => 20,
                'name_en' => 'Obusemachi',
                'name_jp' => '小布施町',
            ],
            [
                'id' => 920,
                'code' => '205435',
                'prefecture_id' => 20,
                'name_en' => 'Takayamamura',
                'name_jp' => '高山村',
            ],
            [
                'id' => 921,
                'code' => '205613',
                'prefecture_id' => 20,
                'name_en' => 'Yamanouchimachi',
                'name_jp' => '山ノ内町',
            ],
            [
                'id' => 922,
                'code' => '205621',
                'prefecture_id' => 20,
                'name_en' => 'Kijimadaira-mura',
                'name_jp' => '木島平村',
            ],
            [
                'id' => 923,
                'code' => '205630',
                'prefecture_id' => 20,
                'name_en' => 'Nozawaonsen-mura',
                'name_jp' => '野沢温泉村',
            ],
            [
                'id' => 924,
                'code' => '205834',
                'prefecture_id' => 20,
                'name_en' => 'Shinanomachi',
                'name_jp' => '信濃町',
            ],
            [
                'id' => 925,
                'code' => '205885',
                'prefecture_id' => 20,
                'name_en' => 'Ogamura',
                'name_jp' => '小川村',
            ],
            [
                'id' => 926,
                'code' => '205907',
                'prefecture_id' => 20,
                'name_en' => 'Iizunamachi',
                'name_jp' => '飯綱町',
            ],
            [
                'id' => 927,
                'code' => '206024',
                'prefecture_id' => 20,
                'name_en' => 'Sakae-mura',
                'name_jp' => '栄村',
            ],
        ];
        DB::table($table_name)->insert($data);
    }
}
